version: "2.0"
services:
  ddelasticsearch:
    image: elasticsearch:2.4
    ports:
      - "19200:9200"
      - "19300:9300"

  ddlogstash:
    image: logstash:2.4
    ports:
      - "15000:5000"
      - "15001:5001/udp"
    volumes: 
      - ./logstash/logstash.conf:/etc/logstash/conf.d/logstash.conf
    command: logstash -f /etc/logstash/conf.d/logstash.conf --auto-reload

  ddkibana:
    image: kibana:4.6
    ports:
      - "15601:5601"
    environment:
      - ELASTICSEARCH_URL=http://localhost:19200

  ddcadvisor:
    image: google/cadvisor:latest
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - "18080:8080"
